### PR TITLE
Choose a theme at runtime

### PR DESCRIPTION
**Pull request by hunter547**
Really enjoying this library and immediately wanted the dark theme all the time, but didn't see that as a feature. Please let me know if you want anything changed. The feature works and has room to scale for new themes.

I would like to declare the `ThemeOptions` type as global (accessible by backroad, backroad-core, and backroad-client) type but couldn't figure out how to do that. Maybe someone can help me with that. Thanks!

### CODE REVIEW

**Comment by sudo-vaibhav** [comment]
Thanks for checking out backroad. Currently I'm on vacation, so please expect some delay in response. One feedback I have is to instead make a config event instead of theme event for sockets since that's more generic and Broadly usable. And then extract what you want from it in the frontend

**Comment by hunter547** [comment]
For sure, can definitely make that change 👍

**Comment by sudo-vaibhav** [comment]
maybe then add a getConfig Function here and make it into a react hook like useBackroadConfig 🤔

**Comment by hunter547** [comment]
Alrighty sir. Added a `config` and `get_config` emit events, made a `getBackroadConfig` function in socket.tsx, and then used that function in a hook on the frontend 👍

**Comment by hunter547** [comment]
Are you able to update the .vscode/settings.json with your vscode configurations? For some reason my vscode wants to format https://github.com/sudomakes/backroad/blob/master/libs/backroad-client/src/lib/socket.tsx differently than yours. Thanks!

**Comment by sudo-vaibhav** [comment]
Good work so far, I also noticed I had made a similar socket event for config fetching for a Google Analytics integration feature I was working on in alpha branch, will copy some of your work, and see how it all looks together.

**Comment by sudo-vaibhav** [comment]
I have inculcated your suggestions in alpha, and it works, also added a disable effect on theme picker when theme is hardcoded by developer. However I noticed the publish pipeline is not working for some reason, will investigate this soon now. To test my code out you can check out the alpha branch of this repo, and it should satisfy what you wanted.

**Comment by hunter547** [comment]
Took a look through and only issue I have is the hook can't emit a new config socket call. Looks like you got rid of the get_config file and function. Seems inconsistent with how you've implemented the other `socket.on` calls in runner.ts. Otherwise looks good to me. Am just worried that if the user wants to get the config adhoc, nothing will be emitted.

**Comment by sudo-vaibhav** [comment]
Changing anything in config anyways restarts the server and loses all state, also it's unlikely that one would want to change things like Google analytics Id on the fly, the config object is more for static configuration which doesn't change.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sudo-vaibhav** [comment]
released on alpha, check out : https://www.npmjs.com/package/@backroad/backroad/v/1.4.0-alpha.2

**Comment by sudo-vaibhav** [comment]
Let me know know if the alpha build meets your needs, then i will go ahead and merge to main

**Comment by hunter547** [comment]
Sure, will do some testing and get back to you today

**Comment by hunter547** [comment]
Everything looks good, except the `console.log` on line 50 of libs\backroad\src\lib\runner\index.ts, presumably because callback is never invoked in the useBackroadConfig hook. Otherwise, looks good to me, would only make that one change so we see the log from the backroad runner.

**Comment by hunter547** [comment]
Changing the `handleConfig` function in the useBackroadConfig hook to this:
```typescript
const handleConfig = (
  config: BackroadConfig,
  callback: (args: undefined) => void
) => {
  setConfig(config);
  callback(undefined);
};
```
now makes it so I see the console log from the backroad runner. Up to you if you want to add that or not

**Comment by sudo-vaibhav** [comment]
so i misssed ACKing the event receipt huh, yeah prolly a good idea to callback

**Pull request merged**
